#!/bin/bash

#--------------------------------
# Configuration
#-------------------------------
TO="maheshgudisetla@gmail.com"
HOSTNAME=$(hostname)
THERSHOLD=80
LOG="/var/log/disk_alert.log"

#------------------------------
# check Disk Usage
#------------------------------
USAGE=$(df / | awk 'NR==2 {print $5}' | tr -d '%')

echo "====================================="
echo " Disk Usage Alert SCript"
echo "====================================="
echo "Server     : $HOSTNAME"
echo "Date       : $(date)"
echo "Disk Usage : $USAGE%"
echo "Thershold  : $THERSHOLD%"
echo "====================================="

#------------------------------------------
# check and send Alert
#------------------------------------------
if [ "$USAGE" -ge "$THERSHOLD" ]; then
    echo " ALERT: Disk usage is HIGH  - $USAGE%"
    
    # send mail
    echo "Subject: Disk Alert on $HOSTNAME

Server   : $HOSTNAME
DAte     : $(date)
Usage    : $USAGE%
Thershold: $THERSHOLD%

$(df -Th /)

PLease free up space!

Regards,
Disk Alert Script" | sendmail $TO
    echo " Alert Email sent to $TO"

else
    echo " Disk Usage is Normal - $USAGE%"
    echo "No Alert Needed"
fi
