---
- name: Setup Cron Jobs
  hosts: servers
  become: yes
  tasks:
   - name: cron for Disk Usage Alert
     cron:
       name: "Disk Usage Alert"
       minute: "*/30"
       job: "/root/maheshg/diskusage"

   - name: cron for root filesystem
     cron:
       name: "root filesystem"
       minute: '0'
       hour: "*/2"
       job: "/root/maheshg/test3"

   - name: cron for System Info
     cron:
       name: "System Info"
       minute: "*/10"
       job: "/root/maheshg/test1"


   - name: cron for Service Monitor
     cron:
       name: "Service Monitor"
       minute: "0"
       hour: "9"
       job: "/root/maheshg/test2"
