- name: Deploy Monitoring Scripts
  hosts: servers
  become: yes
  tasks:
    - name: Copy Disk usage script
      copy:
        src: /root/maheshg/diskusage
        dest: /root/maheshg/diskusage
        mode: '0777'
  
    - name: Copy  Root file script
      copy: 
        src: /root/maheshg/test3
        dest: /root/maheshg/test3
        mode: '0777'

    -  name: Copy System Info Script
       copy: 
         src: /root/maheshg/test1
         dest: /root/maheshg/test1
         mode: '0777'
 
    -  name: Copy Service Monitor Script
       copy:
         src: /root/maheshg/test2
         dest: /root/maheshg/test2
         mode: '0777'
