- name: Deploy Monitoring Scripts
  hosts: servers
  become: yes
  tasks:
    - name: Copy Disk usage script
      copy:
        src: /root/maheshg/diskusage
        dest: /root/maheshg/diskusage
        mode: '0777'
  
    - name: copy  Root file script
      copy: 
        src: /root/maheshg/test3
        dest: /root/maheshg/test3
        mode: '0777'
